### ISSUE TITLE
[1.20.1] Marksmanship Buff Missing Texture

### ISSUE THREAD

**Issue by AetheriMC** [Sweenus/SimplySkills#27]
Minecraft v1.20.1
Fabric v0.14.24
SimplySkills v1.0.0+1.20.1

The marksmanship buff is missing its textures.
![Marksman](https://github.com/Sweenus/SimplySkills/assets/64112227/47a3f4ef-a128-473b-8431-a762f79d44ae)

**Comment by Ayasu** [comment]
Confirming that this is still an issue.
![image](https://github.com/Sweenus/SimplySkills/assets/719362/e3879896-eb05-4f1c-8686-d93d249ae6f1)

**Comment by Sweenus** [comment]
I assume you're both playing MMC2.
This was previously an issue for every spell effect I had that was referencing a vanilla minecraft model/texture, specifically in MMC2. There is a mod in the pack that messes with this, and I've not been able to locate it.

I'll replace the reference to the vanilla arrow texture with a custom texture in the future - this will resolve the issue.
For clarity, this is what you should be seeing:
![Screenshot 2024-02-19 181322](https://github.com/Sweenus/SimplySkills/assets/48658188/8a6fb831-c4b1-47b2-9b57-9452b4362a51)

**Comment by CanecaKun** [comment]
Hello, for clarity,  i´m not playing MMC2.

This bug seemed to always be there since i added the fabric mod for my forge modpack with sinytra conector and forgified api, but i´ll do some tests later to see if i find out what mod is causing it (now my modpack has around 130 mods but this bug has been there since it had 30 so i might be able to locate the mod that´s messing with the textures if it´s not the  connector stuff).

Also i found this same issue with the rogue hability too, i think its the one where you get stacks of might or something when your invisibility is broken by yourself.

**Comment by Sweenus** [comment]
Thank you all for the reports and information!
This should now be fixed as of version 1.1.0
