### ISSUE TITLE
Horses don't count as "pets" for the purposes of Ranger skills

### ISSUE THREAD

**Issue by AngelTechnic** [Sweenus/SimplySkills#5]
Straightforward as the title. Tamed horses are not considered pets by the Ranger's passive and active abilities, meaning that they will not gain stealth from Incognito, nor will a fully upgraded Disengage buff them. In fact, Immobilizing Aura on other pets (such as wolves) will affect tamed horses, preventing them from moving and even hurting them

**Comment by Sweenus** [comment]
Hi there,

The ranger passives work on anything classified as a TameableEntity. The Horse presumably doesn't fall under that umbrella.

Do you think a horse should be affected by the ranger passives? Thematically it doesn't quite match what I had in mind, but I'm open to suggestions.

**Comment by AngelTechnic** [comment]
I think synergies with horses would make for an interesting way to play the class; mounted archers are quite stylish.

**Comment by Sweenus** [comment]
Thanks for your feedback!

I have made changes that allow all the Ranger pet passives to also affect mounts (including modded mounts).
I also noticed that the Tamer & Bonded passives were flipped, so that has also been fixed.
I will push these changes in the next update.

If you have any more feedback/suggestions, please don't hesitate to open another ticket or pop into the Discord. It's super useful for me at this stage of development 🙂
