### ISSUE TITLE
[Suggestion/Balancing Issue] Rogue Sneak Skill

### ISSUE THREAD

**Issue by Joboblock** [Sweenus/SimplySkills#56]
The Rogue Sneak skill adds up to 23 Stacks of "Might", increasing the damage by 230%. With a "Netherite Axe" enchanted with "Sharpness 5" it is possible to deal almost 30 points of damage in a single critical hit, resulting in instant death of players with full "netherite armor" enchanted with "Protection 4".

Combining this with: Strength 2, Agile 8, Netherite Great Hammer (From the Paladins and Priests Mod). With this combination I was able to deal up to 50 points of damage in a single hit. With both "Twinstrike" and "Swordfall" activating, even above 90 damage.

This seems rather unbalanced, I would suggest a maximum of 10 (or even 5) stacks of "Might", to be more balanced.

Alternatively changing "Might" to no longer benefit Axes and Warhammers, to have less maximum damage and fit more with the assasination feel.
(I have never seen an assasin dualwield two Greathammers before, it feels off. Swords feel much better)

With both of these changes (10 Might, only Sword influenced), the maximum damage without chance buffs (Twinstrike, Swordfall), but with "Strength 2" would fall to about 19 damage.

Note, that these numbers may have been influenced by the fact, that i have used a Zombie with armor as a practice dummy (slightly more resistance than player) and picked up small attack damage buffs from the skilltree.

**Comment by Sweenus** [comment]
It has been a few months since I have worked on the mod, so it's not fresh in my brain - but I believe most of the specs are fairly well rounded in terms of DPS.
Rogues do output high burst damage, but this does not translate to high DPS.
The DPS parsing used when I balance hte mod is done using the Dummy mod, here: https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm
