### ISSUE TITLE
Incorrect display of the skill name. And some others

### ISSUE THREAD

**Issue by Atla01** [Sweenus/SimplySkills#58]
While I was translating your mod into Russian I noticed 5 things, 3 of them is a bug and the others are not so important, they are my personal suggestion.

Bug: 
1. The Rogue specialisation has the SiphoningStrikes ability, but instead of its name and description the description of the ShadowstrikeShield ability is used for some reason.
2. There is simply no +3% All spell damage line in the language file, so it can't be translated.
3. Maybe I'm blind, but I didn't see an option to translate the names of tabs with skills of a certain specialisation

The suggestions are to rename two abilities: 
1. Rename Cleric's Altruism skill to invisible aegis, as this is more appropriate for the name of the ability than Altruism (I don't understand what he has to do with it).
2. Rename MutualMending skill to Echoes of healing.
Suggestions are purely subjective and caused by translation difficulties.

**Comment by Sweenus** [comment]
Hi there,
Thank you for your translation work and feedback!
I'll do my best to address your points:

1. This was an error in a previous PR that enabled translated skill trees. I fixed these recently, but I believe you have been working on a slightly outdated lang file.
2. This exists at line 606 of the lang file `  "text.skills.spell_power_additive.title":"§a+3%§f [+] §7All Spell Damage",`. As mentioned above, I think you've been using an outdated lang file.
3. Good catch - these don't have translation entries. I'll add them 👍

I am in the process of adding another skill tree, so I will be adding lang entries over the next few weeks. Is it easiest if I hold your PR untill you've been able to update it with all the new entries? I can give you a heads up when the release is ready, so you can add the translations before I release the build publicly.

In regards to your feedback:
1. It's named Altruism because it involves forgoing your own defence in order to boost your ability to heal others. I think this is a fitting name thematically and would not want to change it.
2. Mutual Mending describes the ability well in English, and I wouldn't want to change it.

If the ability names cause translation issues, I fully trust you do rename them in a way that makes more sense in the native language you're translating to 🙂

**Comment by Sweenus** [comment]
I've now added the skill tree titles to the lang file 🙂

**Comment by Atla01** [comment]
Thanks for the replies. Keeping the PR open would be very handy. As for the Altruism skill, I will revise my translation on it, now I think I missed something.

**Comment by Atla01** [comment]
Ok, as I understand it I won't be able to see some of the changes as they are created for a future version. Looking forward to updates, the mod is good.
