### ISSUE TITLE
What's with the 42 point limit?

### ISSUE THREAD

**Issue by Embeiii** [Sweenus/SimplySkills#64]
I'm not sure if it's intentional or not. But I do want some clarification.

**Comment by Sweenus** [comment]
It is intentional, and the norm for skill trees of this design in video games.

Significant power gain is achievable via the base tree. Limiting points not only keeps the power gain in check, but it allows for theorycrafting of unique builds.

If you're looking for uncapped end-game progression, the latest update added the Ascendancy skill tree, which is unlocked after maxing out the base skill tree, and is uncapped.
