### ISSUE TITLE
information

### ISSUE THREAD

**Issue by Rogenar** [Sweenus/SimplySkills#7]
I installed the Simply Skills mod. I want to give myself skill points with the command, but I couldn't find the commands. Can you tell me how to find your commands?

**Comment by Sweenus** [comment]
Commands are via Pufferfish Skills. For example:

```
/puffish_skills experience add @s simplyskills:tree 10000
/puffish_skills experience add @s simplyskills:wizard 10000
```

**Comment by Rogenar** [comment]
thank you

**Comment by Sweenus** [comment]
Yes, by default only one specialisation can be unlocked. This can be changed in the config.

The exhaustion effect is applied to you because of a passive you picked up in the tree - I'd suggest reading them before you take them. The reason you cannot damage things with your fist is likely because you have weakness when above a certain health threshold, from a berserker passive.

Some of these passives have negative effects, it's important that you read them before taking them.

**Comment by Rogenar** [comment]
I understand. Thank you for your information.

**Comment by integrahellsing62** [comment]
quero resetar minhas skills mas não acho o comando
pderia me dizer qual o comando
I want to reset my skills but I don't think the command could tell me what the command is
